name: Test run workflows

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Show envirement v1
        run: env
      - name: Show ref v1
        run: echo "---> Version from"
